{"uuid": "d2bd2539-2d9d-4de6-9bf9-0985ecae4af5", "children": ["b27ae1fc-2b11-40bc-8566-46fa09817293"], "befores": [{"name": "appium_driver", "status": "broken", "statusDetails": {"message": "urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))\n", "trace": "  File \"/Users/shaikmohamedimran/PycharmProjects/Appium Page Object Model/venv/lib/python3.10/site-packages/pluggy/_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"/Users/shaikmohamedimran/PycharmProjects/Appium Page Object Model/venv/lib/python3.10/site-packages/_pytest/fixtures.py\", line 1129, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/Users/shaikmohamedimran/PycharmProjects/Appium Page Object Model/venv/lib/python3.10/site-packages/_pytest/fixtures.py\", line 901, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/Users/shaikmohamedimran/PycharmProjects/E_farm_Mobile_D2FO/Testcases/conftest.py\", line 107, in appium_driver\n    driver = webdriver.Remote(\"http://127.0.0.1:4723/wd/hub\", desired_cap)\n  File \"/Users/shaikmohamedimran/PycharmProjects/Appium Page Object Model/venv/lib/python3.10/site-packages/appium/webdriver/webdriver.py\", line 235, in __init__\n    super().__init__(\n  File \"/Users/shaikmohamedimran/PycharmProjects/Appium Page Object Model/venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 286, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"/Users/shaikmohamedimran/PycharmProjects/Appium Page Object Model/venv/lib/python3.10/site-packages/appium/webdriver/webdriver.py\", line 327, in start_session\n    response = self.execute(RemoteCommand.NEW_SESSION, w3c_caps)\n  File \"/Users/shaikmohamedimran/PycharmProjects/Appium Page Object Model/venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 438, in execute\n    response = self.command_executor.execute(driver_command, params)\n  File \"/Users/shaikmohamedimran/PycharmProjects/Appium Page Object Model/venv/lib/python3.10/site-packages/selenium/webdriver/remote/remote_connection.py\", line 290, in execute\n    return self._request(command_info[0], url, body=data)\n  File \"/Users/shaikmohamedimran/PycharmProjects/Appium Page Object Model/venv/lib/python3.10/site-packages/selenium/webdriver/remote/remote_connection.py\", line 311, in _request\n    response = self._conn.request(method, url, body=body, headers=headers)\n  File \"/Users/shaikmohamedimran/PycharmProjects/Appium Page Object Model/venv/lib/python3.10/site-packages/urllib3/request.py\", line 78, in request\n    return self.request_encode_body(\n  File \"/Users/shaikmohamedimran/PycharmProjects/Appium Page Object Model/venv/lib/python3.10/site-packages/urllib3/request.py\", line 170, in request_encode_body\n    return self.urlopen(method, url, **extra_kw)\n  File \"/Users/shaikmohamedimran/PycharmProjects/Appium Page Object Model/venv/lib/python3.10/site-packages/urllib3/poolmanager.py\", line 376, in urlopen\n    response = conn.urlopen(method, u.request_uri, **kw)\n  File \"/Users/shaikmohamedimran/PycharmProjects/Appium Page Object Model/venv/lib/python3.10/site-packages/urllib3/connectionpool.py\", line 787, in urlopen\n    retries = retries.increment(\n  File \"/Users/shaikmohamedimran/PycharmProjects/Appium Page Object Model/venv/lib/python3.10/site-packages/urllib3/util/retry.py\", line 550, in increment\n    raise six.reraise(type(error), error, _stacktrace)\n  File \"/Users/shaikmohamedimran/PycharmProjects/Appium Page Object Model/venv/lib/python3.10/site-packages/urllib3/packages/six.py\", line 769, in reraise\n    raise value.with_traceback(tb)\n  File \"/Users/shaikmohamedimran/PycharmProjects/Appium Page Object Model/venv/lib/python3.10/site-packages/urllib3/connectionpool.py\", line 703, in urlopen\n    httplib_response = self._make_request(\n  File \"/Users/shaikmohamedimran/PycharmProjects/Appium Page Object Model/venv/lib/python3.10/site-packages/urllib3/connectionpool.py\", line 449, in _make_request\n    six.raise_from(e, None)\n  File \"<string>\", line 3, in raise_from\n  File \"/Users/shaikmohamedimran/PycharmProjects/Appium Page Object Model/venv/lib/python3.10/site-packages/urllib3/connectionpool.py\", line 444, in _make_request\n    httplib_response = conn.getresponse()\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py\", line 1374, in getresponse\n    response.begin()\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py\", line 318, in begin\n    version, status, reason = self._read_status()\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py\", line 287, in _read_status\n    raise RemoteDisconnected(\"Remote end closed connection without\"\n"}, "start": 1725342649763, "stop": 1725342657635}], "start": 1725342649763, "stop": 1725342657776}